server:
  port: 7071
spring:
  application:
    name: mufeng-generator
  profiles:
    active: local
  config:
    import:
      - nacos:shared-conf.yaml?DEFAULT_GROUP
    cloud:
      nacos:
        # ===== 配置中心设置 =====
        config:
          server-addr: ${spring.cloud.nacos.discovery.server-addr}
          namespace: develop
          group: DEFAULT_GROUP
          file-extension: yaml
          refresh-enabled: true

        # ===== 服务发现设置 =====
        discovery:
          server-addr: localhost:8848
          namespace: public
          group: DEFAULT_GROUP
          register-enabled: true
          service: ${spring.application.name}
          cluster-name: DEFAULT
          metadata:
            version: 1.0
  # 数据源
  datasource:
    druid:
      stat-view-servlet:
        enabled: true # 启用 StatViewServlet
        login-username: admin # 可选，设置监控页登录密码
        login-password: admin
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true # 启用 WebStatFilter
    url: jdbc:mysql://${mf.db.host}:3306/${mf.db.schema}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mf.db.un:root}
    password: ${mf.db.pw}

  jpa:
    show-sql: ${mf.jpa.show-sql}
    hibernate:
      ddl-auto: ${mf.jpa.ddl-auto}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # 推荐使用MySQL8Dialect
        # 配置下划线命名策略
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        jdbc:
          time_zone: Asia/Shanghai # 设置JVM和数据库会话的时区

logging:
  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=${spring.cloud.nacos.config.group}tenant=${spring.cloud.nacos.config.namespace}&username=${spring.cloud.nacos.username}&password=${spring.cloud.nacos.password}&dataId=logback-spring.xml
  level:
    # 显示SQL语句和参数
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.mufeng: DEBUG
    root: info

codegen:
  output-dir: generated-code/